// Column headers of the Zoho Books CSV exports (contacts, vendors, invoices, expenses).
// Used to auto-detect a Zoho export and to route known-but-unmapped columns to the holding area
// without prompting. Source: sample exports supplied by the first migrating customer.

module.exports = {
    contacts: [
        "Created Time", "Last Modified Time", "Display Name", "Company Name",
        "Salutation", "First Name", "Last Name", "Phone",
        "Currency Code", "Notes", "Website", "Status",
        "Created By", "Opening Balance", "Opening Balance Exchange Rate", "Bank Account Payment",
        "Portal Enabled", "Credit Limit", "Customer Sub Type", "Billing Attention",
        "Billing Address", "Billing Street2", "Billing City", "Billing State",
        "Billing Country", "Billing County", "Billing Code", "Billing Phone",
        "Billing Fax", "Billing Latitude", "Billing Longitude", "Shipping Attention",
        "Shipping Address", "Shipping Street2", "Shipping City", "Shipping State",
        "Shipping Country", "Shipping County", "Shipping Code", "Shipping Phone",
        "Shipping Fax", "Shipping Latitude", "Shipping Longitude", "Skype Identity",
        "Facebook", "Twitter", "Department", "Designation",
        "Price List", "Payment Terms", "Payment Terms Label", "Tax Type",
        "Last Sync Time", "Owner Name", "Primary Contact ID", "EmailID",
        "MobilePhone", "Contact ID", "Contact Name", "Contact Type",
        "Taxable", "TaxID", "Tax Name", "Tax Percentage",
        "Exemption Reason", "Tax Authority", "Contact Address ID", "Source",
    ],
    vendors: [
        "Created Time", "Last Modified Time", "Contact ID", "Contact Name",
        "Company Name", "Display Name", "Salutation", "First Name",
        "Last Name", "EmailID", "Phone", "MobilePhone",
        "Currency Code", "Notes", "Website", "Status",
        "Created By", "Payment Terms Label", "Payment Terms", "Skype Identity",
        "Department", "Designation", "Facebook", "Twitter",
        "Track 1099 Payments", "TINType", "TIN", "Price List",
        "Contact Address ID", "Billing Attention", "Billing Address", "Billing Street2",
        "Billing City", "Billing State", "Billing Country", "Billing Code",
        "Billing Phone", "Billing Fax", "Shipping Attention", "Shipping Address",
        "Shipping Street2", "Shipping City", "Shipping State", "Shipping Country",
        "Shipping Code", "Shipping Phone", "Shipping Fax", "Source",
        "Last Sync Time", "Owner Name", "Primary Contact ID",
    ],
    invoices: [
        "Invoice Date", "Invoice ID", "Invoice Number", "Issued Date",
        "Invoice Status", "Customer ID", "Customer Name", "Is Inclusive Tax",
        "Due Date", "PurchaseOrder", "Currency Code", "Exchange Rate",
        "Discount Type", "Is Discount Before Tax", "Template Name", "Entity Discount Percent",
        "SubTotal", "Total", "TotalRetentionAmountFCY", "TotalRetentionAmountBCY",
        "Balance", "Adjustment", "Adjustment Description", "Expected Payment Date",
        "Last Payment Date", "Payment Terms", "Payment Terms Label", "Early Payment Discount Percentage",
        "Early Payment Discount Amount", "Early Payment Discount Due Days", "Notes", "Terms & Conditions",
        "Entity Discount Amount", "Shipping Charge", "Shipping Charge Tax ID", "Shipping Charge Tax Amount",
        "Shipping Charge Tax Name", "Shipping Charge Tax %", "Shipping Charge Tax Type", "Shipping Charge Tax Exemption Code",
        "Item Name", "Item Desc", "Quantity", "Discount",
        "Discount Amount", "Item Total", "Usage unit", "Item Price",
        "Product ID", "Brand", "Sales Order Number", "Expense Reference ID",
        "Recurrence Name", "PayPal", "Authorize.Net", "Google Checkout",
        "Payflow Pro", "Stripe", "Paytm", "2Checkout",
        "Braintree", "Forte", "WorldPay", "Payments Pro",
        "Square", "WePay", "Razorpay", "ICICI EazyPay",
        "GoCardless", "Partial Payments", "Billing Attention", "Billing Address",
        "Billing Street2", "Billing City", "Billing State", "Billing Country",
        "Billing Code", "Billing Phone", "Billing Fax", "Shipping Attention",
        "Shipping Address", "Shipping Street2", "Shipping City", "Shipping State",
        "Shipping Country", "Shipping Code", "Shipping Fax", "Shipping Phone Number",
        "Invoice Level Tax", "Invoice Level Tax %", "Invoice Level Tax Type", "Invoice Level Tax Exemption Reason",
        "Project ID", "Project Name", "Round Off", "Sales person",
        "Subject", "Primary Contact EmailID", "Primary Contact Mobile", "Primary Contact Phone",
        "Estimate Number", "Line Item Category", "Custom Charges", "Shipping Bill#",
        "Shipping Bill Date", "Shipping Bill Total", "PortCode", "Account",
        "Account Code", "Tax ID", "Item Tax", "Item Tax %",
        "Item Tax Amount", "Item Tax Type", "Item Tax Authority", "Item Tax Exemption Reason",
        "Invoice Level Tax Authority", "Kit Combo Item Name",
    ],
    expenses: [
        "Expense Date", "Expense Description", "Expense Account", "Expense Account Code",
        "Paid Through", "Paid Through Account Code", "Vendor", "Project Name",
        "Entry Number", "Currency Code", "Exchange Rate", "Is Inclusive Tax",
        "Mileage Rate", "Mileage Unit", "Distance", "Start Odometer Reading",
        "End Odometer Reading", "Mileage Type", "Vehicle Name", "Claimant Email",
        "Tax Name", "Tax Percentage", "Tax Type", "Item Tax Authority",
        "Tax Amount", "Expense Amount", "Total", "Reference#",
        "Is Billable", "Customer Name", "Expense Reference ID", "Recurrence Name",
        "ExpenseReport Name", "Is Reimbursable",
    ],
};
