-- 022_crm_import_vendors_expenses.sql
-- Import from another system, Release 2 (v7.31.0) — vendors + expenses (+ mileage rows found in expense files).
-- Additive and idempotent: safe to re-run, drops nothing, rewrites no existing data.
-- Builds on 021 (import_batches, import_holding already allow 'vendors'/'expenses' and 'vendor'/'expense').

-- 1. Vendors: contact records for the people/companies the user pays.
-- (Expenses keep their free-text `vendor` column; this table holds the contact details.)
CREATE TABLE IF NOT EXISTS vendors (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  email           TEXT,
  phone           TEXT,
  address         TEXT,
  website         TEXT,
  notes           TEXT,
  track_1099      BOOLEAN NOT NULL DEFAULT FALSE,
  legacy_id       TEXT,
  import_source   TEXT,
  import_batch_id UUID REFERENCES import_batches(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One vendor per name per user (case/space-insensitive).
CREATE UNIQUE INDEX IF NOT EXISTS vendors_user_name_key ON vendors (user_id, lower(btrim(name)));
CREATE INDEX IF NOT EXISTS idx_vendors_user_legacy  ON vendors (user_id, legacy_id) WHERE legacy_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_vendors_import_batch ON vendors (import_batch_id)    WHERE import_batch_id IS NOT NULL;

ALTER TABLE vendors ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "vendors_own" ON vendors;
CREATE POLICY "vendors_own" ON vendors
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

-- 2. Vendor tax IDs (TIN). libsodium-encrypted by the API; separate table so `select *` on vendors
-- never returns ciphertext. last4 is for masked display only.
CREATE TABLE IF NOT EXISTS vendor_tax_ids (
  vendor_id        BIGINT PRIMARY KEY REFERENCES vendors(id) ON DELETE CASCADE,
  user_id          UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tax_id_encrypted TEXT NOT NULL,
  tin_type         TEXT,
  last4            TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE vendor_tax_ids ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "vendor_tax_ids_own" ON vendor_tax_ids;
CREATE POLICY "vendor_tax_ids_own" ON vendor_tax_ids
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

-- 3. Provenance on imported expenses and mileage rows (nullable, no backfill, metadata-only change).
-- NOTE: expenses.rm_id is globally UNIQUE (not per user) and is NOT used for imports.
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS legacy_id       TEXT;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS import_source   TEXT;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS import_batch_id UUID REFERENCES import_batches(id) ON DELETE SET NULL;

ALTER TABLE mileage_logs ADD COLUMN IF NOT EXISTS import_source   TEXT;
ALTER TABLE mileage_logs ADD COLUMN IF NOT EXISTS import_batch_id UUID REFERENCES import_batches(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_expenses_import_batch ON expenses     (import_batch_id) WHERE import_batch_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_mileage_import_batch  ON mileage_logs (import_batch_id) WHERE import_batch_id IS NOT NULL;
